version: "3"

services:
  kali:
    build:
      context: ./kali
      dockerfile: ./Dockerfile
    container_name: 'kali'
    ports:
      - "3389:3389/tcp"
    restart: 'always'
    environment:
      Kali_Password: ${Kali_Password}
  youtrack:
    image: jetbrains/youtrack:2022.1.46592
    container_name: 'youtrack'
    restart: always
    ports:
      - "8080:8080/tcp"
    volumes:
      - ./youtrack/backups:/opt/youtrack/backups